### ISSUE TITLE
Qtwebkit fails compil after compiling QT4 (i686)

### ISSUE THREAD

**Issue by Xdavius** [dvdesolve/pkgbuilds#2]
Hi.
Youre version of QT4 is ok but can't compile qtwebkit from AUR. Error from qt4 missing lib

Can you provide your PKGBUILD for qtwebkit?

(Trying to compile on Archlinux32)

**Comment by dvdesolve** [comment]
I'll take a look soon

**Comment by Xdavius** [comment]
HI. I have made a PKGBUILD that compil on i686 and x86_64 but it's not
perfect :

sha1 verification not OK

passing --no-video in build because I don't know what I miss (gsteamer?)

It's on GitHub/xdavius VRAC folder name qtwebkit.pkgbuild

You need the pathes from qtwebkit AUR.



Le jeu. 13 oct. 2022 à 09:41, viktor drobot ***@***.***> a
écrit :

**Comment by dvdesolve** [comment]
Could you please provide the whole log with error part?
